# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

# Copy source code
COPY src ./src
COPY public ./public

# Build the TypeScript code
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Expose no port (stdio server)

# Default command to run the MCP server
CMD ["node", "dist/server.js"]
